### ISSUE TITLE
Cannot find module 'typpy'

### ISSUE THREAD

**Issue by thewizarodofoz** [keithmorris/node-dotenv-extended#47]
Seems like something is wrong with the dependencies.
We are getting `Cannot find module 'typpy'` when running `import 'dotenv-extended/config';`.

Stack trace:
```internal/modules/cjs/loader.js:818
  throw err;
  ^
Error: Cannot find module 'typpy'
Require stack:
- /service/node_modules/auto-parse/index.js
- /service/node_modules/dotenv-extended/lib/utils/config-from-env.js
- /service/node_modules/dotenv-extended/lib/index.js
- /service/node_modules/dotenv-extended/lib/config.js
- /service/node_modules/dotenv-extended/config.js
- /service/services/parental/dist/index.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:815:15)
    at Function.Module._load (internal/modules/cjs/loader.js:667:27)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/service/node_modules/auto-parse/index.js:3:13)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Module.require (internal/modules/cjs/loader.js:887:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/service/node_modules/auto-parse/index.js',
    '/service/node_modules/dotenv-extended/lib/utils/config-from-env.js',
    '/service/node_modules/dotenv-extended/lib/index.js',
    '/service/node_modules/dotenv-extended/lib/config.js',
    '/service/node_modules/dotenv-extended/config.js',
    '/service/services/parental/dist/index.js'
  ]
}
```

This is the version from yarn.lock:
```
dotenv-extended@^2.8.0:
  version "2.8.0"
  resolved "https://registry.yarnpkg.com/dotenv-extended/-/dotenv-extended-2.8.0.tgz#cfcf73619766cec12c848f93fac36d45560dd562"
  integrity sha512-7R3lSD7JcKkIZ+JnVN4LPJmJ2oR3pi+taqRxVpuod0gpCw/ZjYehEXiqceblP9pQinXY0Gt4nEmVh/1um4c2Mw==
  dependencies:
    auto-parse "^1.3.0"
    camelcase "^5.3.1"
    cross-spawn "^7.0.1"
    dotenv "^8.2.0"
```

**Comment by keithmorris** [comment]
@thewizarodofoz I have not been able to recreate this issue nor have I gotten any more reports of this. Are you still having the issue?
